### ISSUE TITLE
Nf-core module: bamtools/bamtobed

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#1]
### Description of feature

Software/tool: bedtools/bamtobed

Function: Convert Aligned BAM to BED

**Comment by priyanka-surana** [comment]
Works directly from nf-core: https://github.com/nf-core/modules/tree/master/modules/bedtools/bamtobed

**Comment by priyanka-surana** [comment]
This module failed in small dataset testing even after 6 tries, with the last attempt using 30 cpus and 180GB of memory. It fails due to mem limit being reached, which to me seemed absurd especially for a small sample. Replacing it a local module, that optimises for our process, fixed the issue, now the small sample manages to run with just 6 cpus and 36GB memory. The job details shows a max mem of 18M but I don't think that is correct, but we may be able to lower mem and still run successfully.

**Comment by muffato** [comment]
😲 ! `sort` it is, then. (I've seen #3 )
