### ISSUE TITLE
NG50

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#10]
### Description of feature

For NG50, the details are in [Supplementary Note 4: Assessing overall assembly quality](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03451-0/MediaObjects/41586_2021_3451_MOESM1_ESM.pdf) but there is not enough information that I can calculate on my own.

This needs to be calculated for both contig and scaffold.

**Comment by muffato** [comment]
For sure, ToLA/GRIT will also want to compute this statistics. Let's make sure we have a single module
