### ISSUE TITLE
Base pair QV

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#11]
### Description of feature

For Base QV, the information is under [Base pair accuracy (QV) estimate](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03451-0/MediaObjects/41586_2021_3451_MOESM1_ESM.pdf). There are two methods: mapping based using longranger and kmer based using Merqury. As long as we have the [meryl](https://quay.io/repository/biocontainers/merqury) database, the kmer method is straight forward. There are also instructions to create meryl dbs: https://github.com/marbl/merqury/wiki/1.-Prepare-meryl-dbs

**Comment by muffato** [comment]
ToLA have settled on using FastK for the k-mer database, and a variant of Merqury that Yumi has pushed as a Docker image already: https://gitlab.internal.sanger.ac.uk/tol-it/software/docker-images/-/blob/main/fastk/Dockerfile#L32
Ksenia is often showing some QV stats from her work on the polishing pipeline. She can tell which software we should be using - for consistency.
