### ISSUE TITLE
Kmer completeness

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#12]
### Description of feature

They did Kmer completeness with Merqury as well, details under [Quantifying false duplications with k-mers](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03451-0/MediaObjects/41586_2021_3451_MOESM1_ESM.pdf). We can use FastK if needed.

**Comment by muffato** [comment]
Should be a FastK-derivative, like in #11
