### ISSUE TITLE
BUSCO

### ISSUE THREAD

**Issue by priyanka-surana** [sanger-tol/genomenote#26]
### Description of feature

Calculate BUSCO scores from the genome

**Comment by muffato** [comment]
Module being added in https://github.com/nf-core/modules/pull/1239
The BUSCO subworkflow will necessitate extra steps to tar or combine the number of files (by default, BUSCO creates 1 file per BUSCO gene). I will need to implement this to reduce the file usage on `/lustre`, so hopefully by the time you get to work on BUSCO, there should be a script ready.
