### ISSUE TITLE
Deprecate generating the `.genome` file

### ISSUE THREAD

**Issue by muffato** [sanger-tol/genomenote#89]
### Description of feature

We found out today that the `.genome` file is superfluous. HiGlass has an option to draw the chromosome grid from the cool file directly.

We can therefore consider not generating the file at all in this pipeline, which makes things a bit simpler.

**Comment by yumisims** [comment]
.genome is not necessary to be used to display on higlass with mcool map, if you only tend to display mcool, indeed you don't need that. We maintain it as it is used for coverage and other bigwig related tracks.

**Comment by muffato** [comment]
Further discussion with @yumisims in the office: it's a HiGlass UX thing. Some people find it simpler and more convenient to see the grid as a separate file, and find selecting the heatmap to then scroll down and select "2d chrom grid" too cumbersome. So maybe let's just close this ticket and keep generating both ?
